  discriminator: [Function],
      domain: undefined,
      _events: undefined,
      _maxListeners: undefined,
      setMaxListeners: [Function: setMaxListeners],
      getMaxListeners: [Function: getMaxListeners],
      emit: [Function: emit],
      addListener: [Function: addListener],
      on: [Function: addListener],
      prependListener: [Function: prependListener],
      once: [Function: once],
      prependOnceListener: [Function: prependOnceListener],
      removeListener: [Function: removeListener],
      removeAllListeners: [Function: removeAllListeners],
      listeners: [Function: listeners],
      listenerCount: [Function: listenerCount],
      eventNames: [Function: eventNames],
      init: [Function: init],
      syncIndexes: [Function: syncIndexes],
      listIndexes: [Function: init],
      ensureIndexes: [Function: ensureIndexes],
      createIndexes: [Function: createIndexes],
      translateAliases: [Function: translateAliases],
      remove: [Function: remove],
      deleteOne: [Function: deleteOne],
      deleteMany: [Function: deleteMany],
      find: [Function: find],
      findById: [Function: findById],
      findOne: [Function: findOne],
      estimatedDocumentCount: [Function: estimatedDocumentCount],
      countDocuments: [Function: countDocuments],
      count: [Function: count],
      distinct: [Function: distinct],
      where: [Function: where],
      '$where': [Function: $where],
      findOneAndUpdate: [Function],
      findByIdAndUpdate: [Function],
      findOneAndDelete: [Function],
      findByIdAndDelete: [Function],
      findOneAndRemove: [Function],
      findByIdAndRemove: [Function],
      create: [Function: create],
      watch: [Function],
      startSession: [Function],
      insertMany: [Function],
      '$__insertMany': [Function],
      bulkWrite: [Function],
      hydrate: [Function],
      update: [Function: update],
      updateMany: [Function: updateMany],
      updateOne: [Function: updateOne],
      replaceOne: [Function: replaceOne],
      mapReduce: [Function: mapReduce],
      aggregate: [Function: aggregate],
      geoSearch: [Function],
      populate: [Function],
      compile: [Function: compile],
      __subclass: [Function: subclass],
      '$wrapCallback': [Function]
  }